# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Apellidos')),
                ('client_id', models.PositiveIntegerField(blank=True, verbose_name='Identificaci\xf3n')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Direcci\xf3n')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Tel\xe9fono')),
            ],
        ),
    ]
