# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='address',
            new_name='client_address',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='email',
            new_name='client_email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='last_name',
            new_name='client_last_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='client_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='client',
            name='client_phone_number',
            field=models.DecimalField(blank=True, decimal_places=0, default=83021964, max_digits=8, verbose_name='Tel\xe9fono'),
            preserve_default=False,
        ),
    ]
