# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_client_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id_type',
            field=models.CharField(choices=[('noid', 'Sin Identificaci\xf3n'), ('naci', 'C\xe9dula Nacional'), ('pass', 'N\xfamero de Pasaporte'), ('juri', 'C\xe9dula Jur\xeddica')], default='noid', max_length=4, verbose_name='Tipo de Identificaci\xf3n'),
        ),
    ]
