# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productdepartment_name', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Departamento')),
            ],
            options={
                'ordering': ['productdepartment_name'],
                'verbose_name': 'Departamento',
                'verbose_name_plural': '2. Departamentos',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_code'], 'verbose_name': 'Producto', 'verbose_name_plural': '1. Productos'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='product_autoprice',
            field=models.BooleanField(default=0, verbose_name='Precio Autom\xe1tico?'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_barcode',
            field=models.IntegerField(blank=True, default=0, verbose_name='C\xf3digo de Barras'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.IntegerField(default=0, unique=True, verbose_name='C\xf3digo'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Costo \u20a1'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(default=' ', max_length=255, verbose_name='Descripci\xf3n del producto'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_inventory',
            field=models.FloatField(default=0, verbose_name='Existencia en Inventario'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_minimum',
            field=models.FloatField(default=0, verbose_name='M\xednimo en inventario'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Precio sin Impuestos \u20a1'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sellmethod',
            field=models.CharField(choices=[('uni', 'Por Unidad'), ('bul', 'A Granel'), ('kit', 'En Paquete(kit)')], default='uni', max_length=3, verbose_name='Se Vende Por'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sellprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Precio de Venta \u20a1'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Impuestos %'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_useinventory',
            field=models.BooleanField(default=0, verbose_name='Sistema de Inventarios?'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_usetaxes',
            field=models.BooleanField(default=0, verbose_name='Usa Impuestos?'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_utility',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Utilidad %'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.ProductDepartment', verbose_name='Departamento'),
        ),
    ]
