# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160620_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo \u20a1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio sin Impuestos \u20a1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sellprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de Venta \u20a1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Impuestos %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_utility',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Utilidad %'),
        ),
    ]
